name: Chart-Pipeline

on:
  push:
    paths: ["charts/**"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  preparation:
    permissions:
      contents: write
    uses: ./.github/workflows/chart-preparation.yml

  linting:
    needs: [preparation]
    permissions:
      contents: read
    uses: ./.github/workflows/chart-linting.yml

  kubeconform:
    needs: [preparation, linting]
    permissions:
      contents: read
    uses: ./.github/workflows/chart-kubeconform.yml

  unit-testing:
    needs: [preparation, linting, kubeconform]
    permissions:
      contents: read
    uses: ./.github/workflows/chart-unittesting.yml

  testing:
    needs: [preparation, linting, kubeconform, unit-testing]
    permissions:
      contents: read
    uses: ./.github/workflows/chart-testing.yml

  releasing:
    if: github.ref == 'refs/heads/main'
    needs: [preparation, linting, kubeconform, unit-testing, testing]
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/chart-releasing.yml
